[general]
    tags = ["GSAC"]
    description = "Tests for GSAC contest"
    expectedWarningsPattern = "// ;warn:?(.*):(\\d+):? ?(.+)?"
    execCmd = "./run.sh"

[warn]
    execFlags = "--reporter=sarif"
    # regular expression to detect tests
    testNameRegex = ".*Test.*"
    actualWarningsFormat = "SARIF"
    # enabling directory mode
    wildCardInDirectoryMode = "/**/*.—Å"
    actualWarningsFileName = "report.sarif"
    fileNameCaptureGroupOut = 1
    lineCaptureGroupOut = 2
    columnCaptureGroupOut = 3
    messageCaptureGroupOut = 4
    exactWarningsMatch = false
    warningTextHasColumn = true
    warningTextHasLine = true