[general]
    tags = ["warn", "sarif"]
    description = "General configuration for GSAC test suites"
    expectedWarningsPattern = "// ;warn:?(.*):(\\d+):? ?(.+)?"
    execCmd = "./run_save-cli.sh"

[warn]
    exactWarningsMatch = true
    # regular expression to detect tests
    testNameRegex = ".*(EASY|MEDIUM|HARD).*\\.(c|h)"
    actualWarningsFormat = "SARIF"
    # by default, in SARIF mode, it's supposed, that tool will print sarif report into the stdout
    # however, it also could be provided via file
    actualWarningsFileName = "report.sarif"
    fileNameCaptureGroupOut = 1
    lineCaptureGroupOut = 2
    columnCaptureGroupOut = 3
    messageCaptureGroupOut = 4
    warningTextHasColumn = true
    warningTextHasLine = true
